{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ryanchhab",
    "module": "flux-gradle",
    "version": "0.1.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flux-gradle-0.1.0-alpha.jar",
          "url": "flux-gradle-0.1.0-alpha.jar",
          "size": 253139,
          "sha512": "1f4a7b4c4eaa66d212218edb928e781cd73408d5c6bf03d3a235f98cde8a0d7150976893d45712e446cc974a1dbae264b290a74d7f982d4198d8e0aa7bdf09f2",
          "sha256": "610ba0e3e8893021f06e3002d1dfc51f6b56ce4f166c3f8d1c2d8b3bb8228942",
          "sha1": "dded32e950c5372b37f087cb803d308ef374bd1b",
          "md5": "37bd2f86d57b4b1c6e05a91dfd952437"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "r8",
          "version": {
            "requires": "9.4.17"
          }
        }
      ],
      "files": [
        {
          "name": "flux-gradle-0.1.0-alpha.jar",
          "url": "flux-gradle-0.1.0-alpha.jar",
          "size": 253139,
          "sha512": "1f4a7b4c4eaa66d212218edb928e781cd73408d5c6bf03d3a235f98cde8a0d7150976893d45712e446cc974a1dbae264b290a74d7f982d4198d8e0aa7bdf09f2",
          "sha256": "610ba0e3e8893021f06e3002d1dfc51f6b56ce4f166c3f8d1c2d8b3bb8228942",
          "sha1": "dded32e950c5372b37f087cb803d308ef374bd1b",
          "md5": "37bd2f86d57b4b1c6e05a91dfd952437"
        }
      ]
    }
  ]
}
