{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ryanchhab",
    "module": "flux-gradle",
    "version": "0.1.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "flux-gradle-0.1.0-alpha.jar",
          "url": "flux-gradle-0.1.0-alpha.jar",
          "size": 263585,
          "sha512": "747adfd3cffb9e4843da2a357eb4044f6224365a7902956539e6a0fc0371e06adf508df04d3337637a9a6e19a1fe2e16139346b6dee49d4bd90facb0ba0d9d41",
          "sha256": "18e814a272a56e816c94e8505e760672abbc523974533284340b173091889cac",
          "sha1": "5c920b96ab75181bcf73dd1e45c6ad1c55c8c653",
          "md5": "4086561cc571ac64f660fb972fee579f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "r8",
          "version": {
            "requires": "9.4.17"
          }
        }
      ],
      "files": [
        {
          "name": "flux-gradle-0.1.0-alpha.jar",
          "url": "flux-gradle-0.1.0-alpha.jar",
          "size": 263585,
          "sha512": "747adfd3cffb9e4843da2a357eb4044f6224365a7902956539e6a0fc0371e06adf508df04d3337637a9a6e19a1fe2e16139346b6dee49d4bd90facb0ba0d9d41",
          "sha256": "18e814a272a56e816c94e8505e760672abbc523974533284340b173091889cac",
          "sha1": "5c920b96ab75181bcf73dd1e45c6ad1c55c8c653",
          "md5": "4086561cc571ac64f660fb972fee579f"
        }
      ]
    }
  ]
}
