{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ryanchhab",
    "module": "flux-runtime",
    "version": "0.1.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flux-runtime-0.1.0-alpha.aar",
          "url": "flux-runtime-0.1.0-alpha.aar",
          "size": 45853,
          "sha512": "caf4227ab90a8923223eae0af6ce2734e7113c92dceeb8c05670d4d134cf36d1b5ad018cba9145139a7cc9b6b230b1d500fae2fb614f9ae61746f2246e58e89d",
          "sha256": "e4f26aeda059dc54433175de09197eaefaac7217170e64d399bff051cae5d0cf",
          "sha1": "7c43b5c5ada46afe457ecaec89ea1610a84de96c",
          "md5": "a0743daa3fc01b181a6db3ff63763a29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flux-runtime-0.1.0-alpha.aar",
          "url": "flux-runtime-0.1.0-alpha.aar",
          "size": 45853,
          "sha512": "caf4227ab90a8923223eae0af6ce2734e7113c92dceeb8c05670d4d134cf36d1b5ad018cba9145139a7cc9b6b230b1d500fae2fb614f9ae61746f2246e58e89d",
          "sha256": "e4f26aeda059dc54433175de09197eaefaac7217170e64d399bff051cae5d0cf",
          "sha1": "7c43b5c5ada46afe457ecaec89ea1610a84de96c",
          "md5": "a0743daa3fc01b181a6db3ff63763a29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flux-runtime-0.1.0-alpha-sources.jar",
          "url": "flux-runtime-0.1.0-alpha-sources.jar",
          "size": 54171,
          "sha512": "c0b1981c047e1c5995c51810aefc78659f63431bcbe975060b5a3e5769f131d0002b8acb99b05f58c50f9d951cf7a75067b7119b59009a555d50279373e6da16",
          "sha256": "589ff581ce7b6021f922c810ef3d087dc24d35c5da9b5d56091d0b4a4c411d48",
          "sha1": "12fb71415808b256c86a66683e3dae9bf681f693",
          "md5": "e107b493fbeac6e6806b6313a6b55d91"
        }
      ]
    }
  ]
}
