{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ryanchhab",
    "module": "flux-runtime",
    "version": "0.1.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flux-runtime-0.1.0-alpha.aar",
          "url": "flux-runtime-0.1.0-alpha.aar",
          "size": 42335,
          "sha512": "debfcc23ac7b2358be6572e8b8579f8e1a34f3a880fa5aefb1c2d1ff0e50b1bc4d43a68e5abec1bbc0e390610d17756cc82f9ebb6770072bab42d949869817da",
          "sha256": "3363b8c242095393b65f577f5fd54d763af1e793ef1b2fcc5208797b91e7aadf",
          "sha1": "64295f638d3522d00809e37678ac2640ca7a5193",
          "md5": "f6ecc1a33bd5810e1d75c9ddb00132ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flux-runtime-0.1.0-alpha.aar",
          "url": "flux-runtime-0.1.0-alpha.aar",
          "size": 42335,
          "sha512": "debfcc23ac7b2358be6572e8b8579f8e1a34f3a880fa5aefb1c2d1ff0e50b1bc4d43a68e5abec1bbc0e390610d17756cc82f9ebb6770072bab42d949869817da",
          "sha256": "3363b8c242095393b65f577f5fd54d763af1e793ef1b2fcc5208797b91e7aadf",
          "sha1": "64295f638d3522d00809e37678ac2640ca7a5193",
          "md5": "f6ecc1a33bd5810e1d75c9ddb00132ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flux-runtime-0.1.0-alpha-sources.jar",
          "url": "flux-runtime-0.1.0-alpha-sources.jar",
          "size": 49378,
          "sha512": "183d071a2aa0c692e69a2b19089491f1278bcfc93beefda171c86e1427670b78fdfebc24a01d011c71956e552a09dd5bc5b4c91d76cf20243618e8c7702d8d44",
          "sha256": "40657a8cec5d368b4c0b2266f56a47c00b00b82852cb48f43f1a63ce34289f17",
          "sha1": "76e26664a95eaf5606751388e01addb023aee786",
          "md5": "a9685acc72a9a89eb9f83afa1a9ce1f9"
        }
      ]
    }
  ]
}
